services:
  # Config for Web Application
  web:
    container_name: helpdesk
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_UID=${UID:-1002}
        - USER_GID=${GID:-1002}
    user: "${UID:-1002}:${GID:-1002}"
    ports:
      # TODO: Set up HTTPS and map to port 443 instead of 80
      - "80:8080"
    volumes:
      - db_data:/var/www/db
    pid: "host"
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined
        # restart: always # For production, auto restarts if server goes down
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/db/database.sqlite
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}

volumes:
  db_data:
